// Code generated by go-swagger; DO NOT EDIT.

package hotelier

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBookingHandlerFunc turns a function with the right signature into a get booking handler
type GetBookingHandlerFunc func(GetBookingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBookingHandlerFunc) Handle(params GetBookingParams) middleware.Responder {
	return fn(params)
}

// GetBookingHandler interface for that can handle valid get booking params
type GetBookingHandler interface {
	Handle(GetBookingParams) middleware.Responder
}

// NewGetBooking creates a new http.Handler for the get booking operation
func NewGetBooking(ctx *middleware.Context, handler GetBookingHandler) *GetBooking {
	return &GetBooking{Context: ctx, Handler: handler}
}

/*
	GetBooking swagger:route GET /booking hotelier getBooking

Get suitable bookings
*/
type GetBooking struct {
	Context *middleware.Context
	Handler GetBookingHandler
}

func (o *GetBooking) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBookingParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
