services:
  db:
    image: postgres:16.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    expose:
      - 5433
    ports:
      - "5432:5432"
    command: -p 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  hotel:
    container_name: hotel-svc
    build: ./hotel
    depends_on:
      - db
    ports:
      - "8888:8888"
  booking:
    container_name: booking-svc
    build: ./booking
    depends_on:
      - db
    ports:
      - "8880:8880"

volumes:
  postgres_data: