// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/h4x4d/go_hsse_hotels/booking/internal/models"
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateBookingOKCode is the HTTP code returned for type CreateBookingOK
const CreateBookingOKCode int = 200

/*
CreateBookingOK successful operation

swagger:response createBookingOK
*/
type CreateBookingOK struct {

	/*
	  In: Body
	*/
	Payload *CreateBookingOKBody `json:"body,omitempty"`
}

// NewCreateBookingOK creates CreateBookingOK with default headers values
func NewCreateBookingOK() *CreateBookingOK {

	return &CreateBookingOK{}
}

// WithPayload adds the payload to the create booking o k response
func (o *CreateBookingOK) WithPayload(payload *CreateBookingOKBody) *CreateBookingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create booking o k response
func (o *CreateBookingOK) SetPayload(payload *CreateBookingOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBookingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBookingMethodNotAllowedCode is the HTTP code returned for type CreateBookingMethodNotAllowed
const CreateBookingMethodNotAllowedCode int = 405

/*
CreateBookingMethodNotAllowed Incorrect data

swagger:response createBookingMethodNotAllowed
*/
type CreateBookingMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateBookingMethodNotAllowed creates CreateBookingMethodNotAllowed with default headers values
func NewCreateBookingMethodNotAllowed() *CreateBookingMethodNotAllowed {

	return &CreateBookingMethodNotAllowed{}
}

// WithPayload adds the payload to the create booking method not allowed response
func (o *CreateBookingMethodNotAllowed) WithPayload(payload *models.Error) *CreateBookingMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create booking method not allowed response
func (o *CreateBookingMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBookingMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
