// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/go_hsse_hotels/booking/internal/models"
)

// DeleteBookingByIDOKCode is the HTTP code returned for type DeleteBookingByIDOK
const DeleteBookingByIDOKCode int = 200

/*
DeleteBookingByIDOK successful operation

swagger:response deleteBookingByIdOK
*/
type DeleteBookingByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteBookingByIDOK creates DeleteBookingByIDOK with default headers values
func NewDeleteBookingByIDOK() *DeleteBookingByIDOK {

	return &DeleteBookingByIDOK{}
}

// WithPayload adds the payload to the delete booking by Id o k response
func (o *DeleteBookingByIDOK) WithPayload(payload *models.Result) *DeleteBookingByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete booking by Id o k response
func (o *DeleteBookingByIDOK) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBookingByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBookingByIDForbiddenCode is the HTTP code returned for type DeleteBookingByIDForbidden
const DeleteBookingByIDForbiddenCode int = 403

/*
DeleteBookingByIDForbidden No access

swagger:response deleteBookingByIdForbidden
*/
type DeleteBookingByIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBookingByIDForbidden creates DeleteBookingByIDForbidden with default headers values
func NewDeleteBookingByIDForbidden() *DeleteBookingByIDForbidden {

	return &DeleteBookingByIDForbidden{}
}

// WithPayload adds the payload to the delete booking by Id forbidden response
func (o *DeleteBookingByIDForbidden) WithPayload(payload *models.Error) *DeleteBookingByIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete booking by Id forbidden response
func (o *DeleteBookingByIDForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBookingByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBookingByIDNotFoundCode is the HTTP code returned for type DeleteBookingByIDNotFound
const DeleteBookingByIDNotFoundCode int = 404

/*
DeleteBookingByIDNotFound Booking not found

swagger:response deleteBookingByIdNotFound
*/
type DeleteBookingByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBookingByIDNotFound creates DeleteBookingByIDNotFound with default headers values
func NewDeleteBookingByIDNotFound() *DeleteBookingByIDNotFound {

	return &DeleteBookingByIDNotFound{}
}

// WithPayload adds the payload to the delete booking by Id not found response
func (o *DeleteBookingByIDNotFound) WithPayload(payload *models.Error) *DeleteBookingByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete booking by Id not found response
func (o *DeleteBookingByIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBookingByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
