// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteBookingByIDHandlerFunc turns a function with the right signature into a delete booking by id handler
type DeleteBookingByIDHandlerFunc func(DeleteBookingByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBookingByIDHandlerFunc) Handle(params DeleteBookingByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteBookingByIDHandler interface for that can handle valid delete booking by id params
type DeleteBookingByIDHandler interface {
	Handle(DeleteBookingByIDParams, interface{}) middleware.Responder
}

// NewDeleteBookingByID creates a new http.Handler for the delete booking by id operation
func NewDeleteBookingByID(ctx *middleware.Context, handler DeleteBookingByIDHandler) *DeleteBookingByID {
	return &DeleteBookingByID{Context: ctx, Handler: handler}
}

/*
	DeleteBookingByID swagger:route DELETE /booking/{booking_id} customer hotelier deleteBookingById

Delete booking info by id
*/
type DeleteBookingByID struct {
	Context *middleware.Context
	Handler DeleteBookingByIDHandler
}

func (o *DeleteBookingByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteBookingByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
