// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteBookingByIDOKCode is the HTTP code returned for type DeleteBookingByIDOK
const DeleteBookingByIDOKCode int = 200

/*
DeleteBookingByIDOK successful operation

swagger:response deleteBookingByIdOK
*/
type DeleteBookingByIDOK struct {
}

// NewDeleteBookingByIDOK creates DeleteBookingByIDOK with default headers values
func NewDeleteBookingByIDOK() *DeleteBookingByIDOK {

	return &DeleteBookingByIDOK{}
}

// WriteResponse to the client
func (o *DeleteBookingByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteBookingByIDForbiddenCode is the HTTP code returned for type DeleteBookingByIDForbidden
const DeleteBookingByIDForbiddenCode int = 403

/*
DeleteBookingByIDForbidden No access

swagger:response deleteBookingByIdForbidden
*/
type DeleteBookingByIDForbidden struct {
}

// NewDeleteBookingByIDForbidden creates DeleteBookingByIDForbidden with default headers values
func NewDeleteBookingByIDForbidden() *DeleteBookingByIDForbidden {

	return &DeleteBookingByIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteBookingByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DeleteBookingByIDNotFoundCode is the HTTP code returned for type DeleteBookingByIDNotFound
const DeleteBookingByIDNotFoundCode int = 404

/*
DeleteBookingByIDNotFound Booking not found

swagger:response deleteBookingByIdNotFound
*/
type DeleteBookingByIDNotFound struct {
}

// NewDeleteBookingByIDNotFound creates DeleteBookingByIDNotFound with default headers values
func NewDeleteBookingByIDNotFound() *DeleteBookingByIDNotFound {

	return &DeleteBookingByIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteBookingByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
