// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	models2 "github.com/h4x4d/go_hsse_hotels/booking/internal/models"
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetBookingByIDOKCode is the HTTP code returned for type GetBookingByIDOK
const GetBookingByIDOKCode int = 200

/*
GetBookingByIDOK successful operation

swagger:response getBookingByIdOK
*/
type GetBookingByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models2.Booking `json:"body,omitempty"`
}

// NewGetBookingByIDOK creates GetBookingByIDOK with default headers values
func NewGetBookingByIDOK() *GetBookingByIDOK {

	return &GetBookingByIDOK{}
}

// WithPayload adds the payload to the get booking by Id o k response
func (o *GetBookingByIDOK) WithPayload(payload *models2.Booking) *GetBookingByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get booking by Id o k response
func (o *GetBookingByIDOK) SetPayload(payload *models2.Booking) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBookingByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBookingByIDForbiddenCode is the HTTP code returned for type GetBookingByIDForbidden
const GetBookingByIDForbiddenCode int = 403

/*
GetBookingByIDForbidden No access

swagger:response getBookingByIdForbidden
*/
type GetBookingByIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models2.Error `json:"body,omitempty"`
}

// NewGetBookingByIDForbidden creates GetBookingByIDForbidden with default headers values
func NewGetBookingByIDForbidden() *GetBookingByIDForbidden {

	return &GetBookingByIDForbidden{}
}

// WithPayload adds the payload to the get booking by Id forbidden response
func (o *GetBookingByIDForbidden) WithPayload(payload *models2.Error) *GetBookingByIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get booking by Id forbidden response
func (o *GetBookingByIDForbidden) SetPayload(payload *models2.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBookingByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBookingByIDNotFoundCode is the HTTP code returned for type GetBookingByIDNotFound
const GetBookingByIDNotFoundCode int = 404

/*
GetBookingByIDNotFound Booking not found

swagger:response getBookingByIdNotFound
*/
type GetBookingByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models2.Error `json:"body,omitempty"`
}

// NewGetBookingByIDNotFound creates GetBookingByIDNotFound with default headers values
func NewGetBookingByIDNotFound() *GetBookingByIDNotFound {

	return &GetBookingByIDNotFound{}
}

// WithPayload adds the payload to the get booking by Id not found response
func (o *GetBookingByIDNotFound) WithPayload(payload *models2.Error) *GetBookingByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get booking by Id not found response
func (o *GetBookingByIDNotFound) SetPayload(payload *models2.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBookingByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
