// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateBookingOKCode is the HTTP code returned for type UpdateBookingOK
const UpdateBookingOKCode int = 200

/*
UpdateBookingOK successful operation

swagger:response updateBookingOK
*/
type UpdateBookingOK struct {

	/*
	  In: Body
	*/
	Payload *UpdateBookingOKBody `json:"body,omitempty"`
}

// NewUpdateBookingOK creates UpdateBookingOK with default headers values
func NewUpdateBookingOK() *UpdateBookingOK {

	return &UpdateBookingOK{}
}

// WithPayload adds the payload to the update booking o k response
func (o *UpdateBookingOK) WithPayload(payload *UpdateBookingOKBody) *UpdateBookingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update booking o k response
func (o *UpdateBookingOK) SetPayload(payload *UpdateBookingOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateBookingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateBookingForbiddenCode is the HTTP code returned for type UpdateBookingForbidden
const UpdateBookingForbiddenCode int = 403

/*
UpdateBookingForbidden No access

swagger:response updateBookingForbidden
*/
type UpdateBookingForbidden struct {
}

// NewUpdateBookingForbidden creates UpdateBookingForbidden with default headers values
func NewUpdateBookingForbidden() *UpdateBookingForbidden {

	return &UpdateBookingForbidden{}
}

// WriteResponse to the client
func (o *UpdateBookingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// UpdateBookingMethodNotAllowedCode is the HTTP code returned for type UpdateBookingMethodNotAllowed
const UpdateBookingMethodNotAllowedCode int = 405

/*
UpdateBookingMethodNotAllowed Incorrect data

swagger:response updateBookingMethodNotAllowed
*/
type UpdateBookingMethodNotAllowed struct {
}

// NewUpdateBookingMethodNotAllowed creates UpdateBookingMethodNotAllowed with default headers values
func NewUpdateBookingMethodNotAllowed() *UpdateBookingMethodNotAllowed {

	return &UpdateBookingMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateBookingMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
