// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateBookingHandlerFunc turns a function with the right signature into a update booking handler
type UpdateBookingHandlerFunc func(UpdateBookingParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateBookingHandlerFunc) Handle(params UpdateBookingParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateBookingHandler interface for that can handle valid update booking params
type UpdateBookingHandler interface {
	Handle(UpdateBookingParams, interface{}) middleware.Responder
}

// NewUpdateBooking creates a new http.Handler for the update booking operation
func NewUpdateBooking(ctx *middleware.Context, handler UpdateBookingHandler) *UpdateBooking {
	return &UpdateBooking{Context: ctx, Handler: handler}
}

/*
	UpdateBooking swagger:route PUT /booking/{booking_id} customer hotelier updateBooking

Update booking
*/
type UpdateBooking struct {
	Context *middleware.Context
	Handler UpdateBookingHandler
}

func (o *UpdateBooking) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateBookingParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// UpdateBookingOKBody update booking o k body
//
// swagger:model UpdateBookingOKBody
type UpdateBookingOKBody struct {

	// booking id
	BookingID int64 `json:"booking_id,omitempty"`
}

// Validate validates this update booking o k body
func (o *UpdateBookingOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update booking o k body based on context it is used
func (o *UpdateBookingOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateBookingOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateBookingOKBody) UnmarshalBinary(b []byte) error {
	var res UpdateBookingOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
