// Code generated by go-swagger; DO NOT EDIT.

package hotel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateHotelHandlerFunc turns a function with the right signature into a update hotel handler
type UpdateHotelHandlerFunc func(UpdateHotelParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateHotelHandlerFunc) Handle(params UpdateHotelParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateHotelHandler interface for that can handle valid update hotel params
type UpdateHotelHandler interface {
	Handle(UpdateHotelParams, interface{}) middleware.Responder
}

// NewUpdateHotel creates a new http.Handler for the update hotel operation
func NewUpdateHotel(ctx *middleware.Context, handler UpdateHotelHandler) *UpdateHotel {
	return &UpdateHotel{Context: ctx, Handler: handler}
}

/*
	UpdateHotel swagger:route PUT /hotel/{hotel_id} hotel updateHotel

Update hotel
*/
type UpdateHotel struct {
	Context *middleware.Context
	Handler UpdateHotelHandler
}

func (o *UpdateHotel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateHotelParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// UpdateHotelOKBody update hotel o k body
//
// swagger:model UpdateHotelOKBody
type UpdateHotelOKBody struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this update hotel o k body
func (o *UpdateHotelOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update hotel o k body based on context it is used
func (o *UpdateHotelOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateHotelOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateHotelOKBody) UnmarshalBinary(b []byte) error {
	var res UpdateHotelOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
