// Code generated by go-swagger; DO NOT EDIT.

package hotel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/h4x4d/go_hsse_hotels/hotel/internal/models"
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateHotelOKCode is the HTTP code returned for type CreateHotelOK
const CreateHotelOKCode int = 200

/*
CreateHotelOK successful operation

swagger:response createHotelOK
*/
type CreateHotelOK struct {

	/*
	  In: Body
	*/
	Payload *CreateHotelOKBody `json:"body,omitempty"`
}

// NewCreateHotelOK creates CreateHotelOK with default headers values
func NewCreateHotelOK() *CreateHotelOK {

	return &CreateHotelOK{}
}

// WithPayload adds the payload to the create hotel o k response
func (o *CreateHotelOK) WithPayload(payload *CreateHotelOKBody) *CreateHotelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create hotel o k response
func (o *CreateHotelOK) SetPayload(payload *CreateHotelOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateHotelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateHotelForbiddenCode is the HTTP code returned for type CreateHotelForbidden
const CreateHotelForbiddenCode int = 403

/*
CreateHotelForbidden No access

swagger:response createHotelForbidden
*/
type CreateHotelForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateHotelForbidden creates CreateHotelForbidden with default headers values
func NewCreateHotelForbidden() *CreateHotelForbidden {

	return &CreateHotelForbidden{}
}

// WithPayload adds the payload to the create hotel forbidden response
func (o *CreateHotelForbidden) WithPayload(payload *models.Error) *CreateHotelForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create hotel forbidden response
func (o *CreateHotelForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateHotelForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateHotelMethodNotAllowedCode is the HTTP code returned for type CreateHotelMethodNotAllowed
const CreateHotelMethodNotAllowedCode int = 405

/*
CreateHotelMethodNotAllowed Incorrect data

swagger:response createHotelMethodNotAllowed
*/
type CreateHotelMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateHotelMethodNotAllowed creates CreateHotelMethodNotAllowed with default headers values
func NewCreateHotelMethodNotAllowed() *CreateHotelMethodNotAllowed {

	return &CreateHotelMethodNotAllowed{}
}

// WithPayload adds the payload to the create hotel method not allowed response
func (o *CreateHotelMethodNotAllowed) WithPayload(payload *models.Error) *CreateHotelMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create hotel method not allowed response
func (o *CreateHotelMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateHotelMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
