// Code generated by go-swagger; DO NOT EDIT.

package hotel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/go_hsse_hotels/hotel/internal/models"
)

// DeleteHotelByIDOKCode is the HTTP code returned for type DeleteHotelByIDOK
const DeleteHotelByIDOKCode int = 200

/*
DeleteHotelByIDOK successful operation

swagger:response deleteHotelByIdOK
*/
type DeleteHotelByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteHotelByIDOK creates DeleteHotelByIDOK with default headers values
func NewDeleteHotelByIDOK() *DeleteHotelByIDOK {

	return &DeleteHotelByIDOK{}
}

// WithPayload adds the payload to the delete hotel by Id o k response
func (o *DeleteHotelByIDOK) WithPayload(payload *models.Result) *DeleteHotelByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete hotel by Id o k response
func (o *DeleteHotelByIDOK) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHotelByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteHotelByIDNotFoundCode is the HTTP code returned for type DeleteHotelByIDNotFound
const DeleteHotelByIDNotFoundCode int = 404

/*
DeleteHotelByIDNotFound Hotel not found

swagger:response deleteHotelByIdNotFound
*/
type DeleteHotelByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteHotelByIDNotFound creates DeleteHotelByIDNotFound with default headers values
func NewDeleteHotelByIDNotFound() *DeleteHotelByIDNotFound {

	return &DeleteHotelByIDNotFound{}
}

// WithPayload adds the payload to the delete hotel by Id not found response
func (o *DeleteHotelByIDNotFound) WithPayload(payload *models.Error) *DeleteHotelByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete hotel by Id not found response
func (o *DeleteHotelByIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHotelByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
