// Code generated by go-swagger; DO NOT EDIT.

package hotel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteHotelByIDHandlerFunc turns a function with the right signature into a delete hotel by id handler
type DeleteHotelByIDHandlerFunc func(DeleteHotelByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteHotelByIDHandlerFunc) Handle(params DeleteHotelByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteHotelByIDHandler interface for that can handle valid delete hotel by id params
type DeleteHotelByIDHandler interface {
	Handle(DeleteHotelByIDParams, interface{}) middleware.Responder
}

// NewDeleteHotelByID creates a new http.Handler for the delete hotel by id operation
func NewDeleteHotelByID(ctx *middleware.Context, handler DeleteHotelByIDHandler) *DeleteHotelByID {
	return &DeleteHotelByID{Context: ctx, Handler: handler}
}

/*
	DeleteHotelByID swagger:route DELETE /hotel/{hotel_id} hotel deleteHotelById

Delete hotel info by id
*/
type DeleteHotelByID struct {
	Context *middleware.Context
	Handler DeleteHotelByIDHandler
}

func (o *DeleteHotelByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteHotelByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
