// Code generated by go-swagger; DO NOT EDIT.

package hotel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetHotelsParams creates a new GetHotelsParams object
//
// There are no default values defined in the spec.
func NewGetHotelsParams() GetHotelsParams {

	return GetHotelsParams{}
}

// GetHotelsParams contains all the bound params for the get hotels operation
// typically these are obtained from a http.Request
//
// swagger:parameters get_hotels
type GetHotelsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	City *string
	/*
	  In: query
	*/
	HotelClass *int64
	/*
	  In: query
	*/
	Name *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetHotelsParams() beforehand.
func (o *GetHotelsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCity, qhkCity, _ := qs.GetOK("city")
	if err := o.bindCity(qCity, qhkCity, route.Formats); err != nil {
		res = append(res, err)
	}

	qHotelClass, qhkHotelClass, _ := qs.GetOK("hotel_class")
	if err := o.bindHotelClass(qHotelClass, qhkHotelClass, route.Formats); err != nil {
		res = append(res, err)
	}

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCity binds and validates parameter City from query.
func (o *GetHotelsParams) bindCity(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.City = &raw

	return nil
}

// bindHotelClass binds and validates parameter HotelClass from query.
func (o *GetHotelsParams) bindHotelClass(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("hotel_class", "query", "int64", raw)
	}
	o.HotelClass = &value

	if err := o.validateHotelClass(formats); err != nil {
		return err
	}

	return nil
}

// validateHotelClass carries on validations for parameter HotelClass
func (o *GetHotelsParams) validateHotelClass(formats strfmt.Registry) error {

	if err := validate.EnumCase("hotel_class", "query", *o.HotelClass, []interface{}{1, 2, 3, 4, 5}, true); err != nil {
		return err
	}

	return nil
}

// bindName binds and validates parameter Name from query.
func (o *GetHotelsParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Name = &raw

	return nil
}
