// Code generated by go-swagger; DO NOT EDIT.

package hotel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetHotelByIDHandlerFunc turns a function with the right signature into a get hotel by id handler
type GetHotelByIDHandlerFunc func(GetHotelByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHotelByIDHandlerFunc) Handle(params GetHotelByIDParams) middleware.Responder {
	return fn(params)
}

// GetHotelByIDHandler interface for that can handle valid get hotel by id params
type GetHotelByIDHandler interface {
	Handle(GetHotelByIDParams) middleware.Responder
}

// NewGetHotelByID creates a new http.Handler for the get hotel by id operation
func NewGetHotelByID(ctx *middleware.Context, handler GetHotelByIDHandler) *GetHotelByID {
	return &GetHotelByID{Context: ctx, Handler: handler}
}

/*
	GetHotelByID swagger:route GET /hotel/{hotel_id} hotel getHotelById

Get hotel info by id
*/
type GetHotelByID struct {
	Context *middleware.Context
	Handler GetHotelByIDHandler
}

func (o *GetHotelByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetHotelByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
