// Code generated by go-swagger; DO NOT EDIT.

package hotel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/go_hsse_hotels/hotel/internal/models"
)

// GetHotelsOKCode is the HTTP code returned for type GetHotelsOK
const GetHotelsOKCode int = 200

/*
GetHotelsOK successful operation

swagger:response getHotelsOK
*/
type GetHotelsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Hotel `json:"body,omitempty"`
}

// NewGetHotelsOK creates GetHotelsOK with default headers values
func NewGetHotelsOK() *GetHotelsOK {

	return &GetHotelsOK{}
}

// WithPayload adds the payload to the get hotels o k response
func (o *GetHotelsOK) WithPayload(payload []*models.Hotel) *GetHotelsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hotels o k response
func (o *GetHotelsOK) SetPayload(payload []*models.Hotel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHotelsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Hotel, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetHotelsNotFoundCode is the HTTP code returned for type GetHotelsNotFound
const GetHotelsNotFoundCode int = 404

/*
GetHotelsNotFound Suitable hotels not found

swagger:response getHotelsNotFound
*/
type GetHotelsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetHotelsNotFound creates GetHotelsNotFound with default headers values
func NewGetHotelsNotFound() *GetHotelsNotFound {

	return &GetHotelsNotFound{}
}

// WithPayload adds the payload to the get hotels not found response
func (o *GetHotelsNotFound) WithPayload(payload *models.Error) *GetHotelsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hotels not found response
func (o *GetHotelsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHotelsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
