// Code generated by go-swagger; DO NOT EDIT.

package hotel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/go_hsse_hotels/hotel/internal/models"
)

// UpdateHotelHandlerFunc turns a function with the right signature into a update hotel handler
type UpdateHotelHandlerFunc func(UpdateHotelParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateHotelHandlerFunc) Handle(params UpdateHotelParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// UpdateHotelHandler interface for that can handle valid update hotel params
type UpdateHotelHandler interface {
	Handle(UpdateHotelParams, *models.User) middleware.Responder
}

// NewUpdateHotel creates a new http.Handler for the update hotel operation
func NewUpdateHotel(ctx *middleware.Context, handler UpdateHotelHandler) *UpdateHotel {
	return &UpdateHotel{Context: ctx, Handler: handler}
}

/*
	UpdateHotel swagger:route PUT /hotel/{hotel_id} hotel updateHotel

Update hotel
*/
type UpdateHotel struct {
	Context *middleware.Context
	Handler UpdateHotelHandler
}

func (o *UpdateHotel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateHotelParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
