// Code generated by go-swagger; DO NOT EDIT.

package hotel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/h4x4d/go_hsse_hotels/hotel/internal/models"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewUpdateHotelParams creates a new UpdateHotelParams object
//
// There are no default values defined in the spec.
func NewUpdateHotelParams() UpdateHotelParams {

	return UpdateHotelParams{}
}

// UpdateHotelParams contains all the bound params for the update hotel operation
// typically these are obtained from a http.Request
//
// swagger:parameters update_hotel
type UpdateHotelParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of hotel to change
	  Required: true
	  In: path
	*/
	HotelID int64
	/*
	  Required: true
	  In: body
	*/
	Object *models.Hotel
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateHotelParams() beforehand.
func (o *UpdateHotelParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rHotelID, rhkHotelID, _ := route.Params.GetOK("hotel_id")
	if err := o.bindHotelID(rHotelID, rhkHotelID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Hotel
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("object", "body", ""))
			} else {
				res = append(res, errors.NewParseError("object", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Object = &body
			}
		}
	} else {
		res = append(res, errors.Required("object", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindHotelID binds and validates parameter HotelID from path.
func (o *UpdateHotelParams) bindHotelID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("hotel_id", "path", "int64", raw)
	}
	o.HotelID = value

	return nil
}
