// Code generated by go-swagger; DO NOT EDIT.

package hotel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/h4x4d/go_hsse_hotels/hotel/internal/models"
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateHotelOKCode is the HTTP code returned for type UpdateHotelOK
const UpdateHotelOKCode int = 200

/*
UpdateHotelOK successful operation

swagger:response updateHotelOK
*/
type UpdateHotelOK struct {

	/*
	  In: Body
	*/
	Payload *UpdateHotelOKBody `json:"body,omitempty"`
}

// NewUpdateHotelOK creates UpdateHotelOK with default headers values
func NewUpdateHotelOK() *UpdateHotelOK {

	return &UpdateHotelOK{}
}

// WithPayload adds the payload to the update hotel o k response
func (o *UpdateHotelOK) WithPayload(payload *UpdateHotelOKBody) *UpdateHotelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update hotel o k response
func (o *UpdateHotelOK) SetPayload(payload *UpdateHotelOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHotelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateHotelForbiddenCode is the HTTP code returned for type UpdateHotelForbidden
const UpdateHotelForbiddenCode int = 403

/*
UpdateHotelForbidden No access

swagger:response updateHotelForbidden
*/
type UpdateHotelForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateHotelForbidden creates UpdateHotelForbidden with default headers values
func NewUpdateHotelForbidden() *UpdateHotelForbidden {

	return &UpdateHotelForbidden{}
}

// WithPayload adds the payload to the update hotel forbidden response
func (o *UpdateHotelForbidden) WithPayload(payload *models.Error) *UpdateHotelForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update hotel forbidden response
func (o *UpdateHotelForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHotelForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateHotelMethodNotAllowedCode is the HTTP code returned for type UpdateHotelMethodNotAllowed
const UpdateHotelMethodNotAllowedCode int = 405

/*
UpdateHotelMethodNotAllowed Incorrect data

swagger:response updateHotelMethodNotAllowed
*/
type UpdateHotelMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateHotelMethodNotAllowed creates UpdateHotelMethodNotAllowed with default headers values
func NewUpdateHotelMethodNotAllowed() *UpdateHotelMethodNotAllowed {

	return &UpdateHotelMethodNotAllowed{}
}

// WithPayload adds the payload to the update hotel method not allowed response
func (o *UpdateHotelMethodNotAllowed) WithPayload(payload *models.Error) *UpdateHotelMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update hotel method not allowed response
func (o *UpdateHotelMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHotelMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
