// Code generated by go-swagger; DO NOT EDIT.

package room

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateRoomHandlerFunc turns a function with the right signature into a create room handler
type CreateRoomHandlerFunc func(CreateRoomParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateRoomHandlerFunc) Handle(params CreateRoomParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateRoomHandler interface for that can handle valid create room params
type CreateRoomHandler interface {
	Handle(CreateRoomParams, interface{}) middleware.Responder
}

// NewCreateRoom creates a new http.Handler for the create room operation
func NewCreateRoom(ctx *middleware.Context, handler CreateRoomHandler) *CreateRoom {
	return &CreateRoom{Context: ctx, Handler: handler}
}

/*
	CreateRoom swagger:route POST /hotel/room room createRoom

Create room
*/
type CreateRoom struct {
	Context *middleware.Context
	Handler CreateRoomHandler
}

func (o *CreateRoom) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateRoomParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateRoomOKBody create room o k body
//
// swagger:model CreateRoomOKBody
type CreateRoomOKBody struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this create room o k body
func (o *CreateRoomOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create room o k body based on context it is used
func (o *CreateRoomOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateRoomOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateRoomOKBody) UnmarshalBinary(b []byte) error {
	var res CreateRoomOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
