// Code generated by go-swagger; DO NOT EDIT.

package room

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateRoomOKCode is the HTTP code returned for type CreateRoomOK
const CreateRoomOKCode int = 200

/*
CreateRoomOK successful operation

swagger:response createRoomOK
*/
type CreateRoomOK struct {

	/*
	  In: Body
	*/
	Payload *CreateRoomOKBody `json:"body,omitempty"`
}

// NewCreateRoomOK creates CreateRoomOK with default headers values
func NewCreateRoomOK() *CreateRoomOK {

	return &CreateRoomOK{}
}

// WithPayload adds the payload to the create room o k response
func (o *CreateRoomOK) WithPayload(payload *CreateRoomOKBody) *CreateRoomOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create room o k response
func (o *CreateRoomOK) SetPayload(payload *CreateRoomOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRoomOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateRoomForbiddenCode is the HTTP code returned for type CreateRoomForbidden
const CreateRoomForbiddenCode int = 403

/*
CreateRoomForbidden No access

swagger:response createRoomForbidden
*/
type CreateRoomForbidden struct {
}

// NewCreateRoomForbidden creates CreateRoomForbidden with default headers values
func NewCreateRoomForbidden() *CreateRoomForbidden {

	return &CreateRoomForbidden{}
}

// WriteResponse to the client
func (o *CreateRoomForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// CreateRoomMethodNotAllowedCode is the HTTP code returned for type CreateRoomMethodNotAllowed
const CreateRoomMethodNotAllowedCode int = 405

/*
CreateRoomMethodNotAllowed Incorrect data

swagger:response createRoomMethodNotAllowed
*/
type CreateRoomMethodNotAllowed struct {
}

// NewCreateRoomMethodNotAllowed creates CreateRoomMethodNotAllowed with default headers values
func NewCreateRoomMethodNotAllowed() *CreateRoomMethodNotAllowed {

	return &CreateRoomMethodNotAllowed{}
}

// WriteResponse to the client
func (o *CreateRoomMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
