// Code generated by go-swagger; DO NOT EDIT.

package room

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteRoomByIDHandlerFunc turns a function with the right signature into a delete room by id handler
type DeleteRoomByIDHandlerFunc func(DeleteRoomByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRoomByIDHandlerFunc) Handle(params DeleteRoomByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteRoomByIDHandler interface for that can handle valid delete room by id params
type DeleteRoomByIDHandler interface {
	Handle(DeleteRoomByIDParams, interface{}) middleware.Responder
}

// NewDeleteRoomByID creates a new http.Handler for the delete room by id operation
func NewDeleteRoomByID(ctx *middleware.Context, handler DeleteRoomByIDHandler) *DeleteRoomByID {
	return &DeleteRoomByID{Context: ctx, Handler: handler}
}

/*
	DeleteRoomByID swagger:route DELETE /hotel/room/{room_id} room deleteRoomById

Delete room info by id
*/
type DeleteRoomByID struct {
	Context *middleware.Context
	Handler DeleteRoomByIDHandler
}

func (o *DeleteRoomByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteRoomByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
