// Code generated by go-swagger; DO NOT EDIT.

package room

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateRoomHandlerFunc turns a function with the right signature into a update room handler
type UpdateRoomHandlerFunc func(UpdateRoomParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateRoomHandlerFunc) Handle(params UpdateRoomParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateRoomHandler interface for that can handle valid update room params
type UpdateRoomHandler interface {
	Handle(UpdateRoomParams, interface{}) middleware.Responder
}

// NewUpdateRoom creates a new http.Handler for the update room operation
func NewUpdateRoom(ctx *middleware.Context, handler UpdateRoomHandler) *UpdateRoom {
	return &UpdateRoom{Context: ctx, Handler: handler}
}

/*
	UpdateRoom swagger:route PUT /hotel/room/{room_id} room updateRoom

Update room
*/
type UpdateRoom struct {
	Context *middleware.Context
	Handler UpdateRoomHandler
}

func (o *UpdateRoom) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateRoomParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// UpdateRoomOKBody update room o k body
//
// swagger:model UpdateRoomOKBody
type UpdateRoomOKBody struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this update room o k body
func (o *UpdateRoomOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update room o k body based on context it is used
func (o *UpdateRoomOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateRoomOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateRoomOKBody) UnmarshalBinary(b []byte) error {
	var res UpdateRoomOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
