// Code generated by go-swagger; DO NOT EDIT.

// Package restapi hotels.booking
//
//	MTS HSSE Go project | Booking svc
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.3.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
