// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "MTS HSSE Go project | Booking svc",
    "title": "hotels.booking",
    "version": "0.3.0"
  },
  "paths": {
    "/booking": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "hotelier"
        ],
        "summary": "Get suitable bookings",
        "operationId": "get_booking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "hotel_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Booking"
              }
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Booking not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "customer"
        ],
        "summary": "Create booking",
        "operationId": "create_booking",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "booking_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/booking/{booking_id}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "customer",
          "hotelier"
        ],
        "summary": "Get booking info by id",
        "operationId": "get_booking_by_id",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of booking to return",
            "name": "booking_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Booking not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "customer",
          "hotelier"
        ],
        "summary": "Update booking",
        "operationId": "update_booking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of booking to change",
            "name": "booking_id",
            "in": "path",
            "required": true
          },
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "booking_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Booking": {
      "type": "object",
      "required": [
        "date_from",
        "date_to",
        "hotel_id"
      ],
      "properties": {
        "booking_id": {
          "type": "integer",
          "format": "int64"
        },
        "date_from": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
          "example": "2024-12-31"
        },
        "date_to": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
          "example": "2025-01-11"
        },
        "full_cost": {
          "type": "integer",
          "format": "int64"
        },
        "hotel_id": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "description": "status of booking",
          "type": "string",
          "enum": [
            "Waiting",
            "Payed",
            "Confirmed",
            "Finished"
          ]
        },
        "user_id": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "error_status_code"
      ],
      "properties": {
        "error_message": {
          "type": "string"
        },
        "error_status_code": {
          "type": "integer"
        }
      }
    },
    "Hotel": {
      "type": "object",
      "required": [
        "name",
        "city",
        "address"
      ],
      "properties": {
        "address": {
          "type": "string",
          "example": "Red Square №1"
        },
        "city": {
          "type": "string",
          "example": "Moscow"
        },
        "cost": {
          "type": "integer",
          "format": "int64"
        },
        "hotel_class": {
          "description": "number of stars of hotel",
          "type": "integer",
          "enum": [
            0,
            1,
            2,
            3,
            4,
            5
          ]
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string",
          "example": "Radisson"
        }
      }
    },
    "Result": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Customer operations",
      "name": "customer"
    },
    {
      "description": "Hotelier operations",
      "name": "hotelier"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "MTS HSSE Go project | Booking svc",
    "title": "hotels.booking",
    "version": "0.3.0"
  },
  "paths": {
    "/booking": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "hotelier"
        ],
        "summary": "Get suitable bookings",
        "operationId": "get_booking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "hotel_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Booking"
              }
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Booking not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "customer"
        ],
        "summary": "Create booking",
        "operationId": "create_booking",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "booking_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/booking/{booking_id}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "customer",
          "hotelier"
        ],
        "summary": "Get booking info by id",
        "operationId": "get_booking_by_id",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of booking to return",
            "name": "booking_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Booking not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "customer",
          "hotelier"
        ],
        "summary": "Update booking",
        "operationId": "update_booking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of booking to change",
            "name": "booking_id",
            "in": "path",
            "required": true
          },
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "booking_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Booking": {
      "type": "object",
      "required": [
        "date_from",
        "date_to",
        "hotel_id"
      ],
      "properties": {
        "booking_id": {
          "type": "integer",
          "format": "int64"
        },
        "date_from": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
          "example": "2024-12-31"
        },
        "date_to": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
          "example": "2025-01-11"
        },
        "full_cost": {
          "type": "integer",
          "format": "int64"
        },
        "hotel_id": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "description": "status of booking",
          "type": "string",
          "enum": [
            "Waiting",
            "Payed",
            "Confirmed",
            "Finished"
          ]
        },
        "user_id": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "error_status_code"
      ],
      "properties": {
        "error_message": {
          "type": "string"
        },
        "error_status_code": {
          "type": "integer"
        }
      }
    },
    "Hotel": {
      "type": "object",
      "required": [
        "name",
        "city",
        "address"
      ],
      "properties": {
        "address": {
          "type": "string",
          "example": "Red Square №1"
        },
        "city": {
          "type": "string",
          "example": "Moscow"
        },
        "cost": {
          "type": "integer",
          "format": "int64"
        },
        "hotel_class": {
          "description": "number of stars of hotel",
          "type": "integer",
          "enum": [
            0,
            1,
            2,
            3,
            4,
            5
          ]
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string",
          "example": "Radisson"
        }
      }
    },
    "Result": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Customer operations",
      "name": "customer"
    },
    {
      "description": "Hotelier operations",
      "name": "hotelier"
    }
  ]
}`))
}
