// Code generated by go-swagger; DO NOT EDIT.

// Package restapi hotels.auth
//
//	MTS HSSE Go project | Auth svc
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
