// Code generated by go-swagger; DO NOT EDIT.

package room

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/go_hsse_hotels/hotel/internal/models"
)

// CreateRoomOKCode is the HTTP code returned for type CreateRoomOK
const CreateRoomOKCode int = 200

/*
CreateRoomOK successful operation

swagger:response createRoomOK
*/
type CreateRoomOK struct {

	/*
	  In: Body
	*/
	Payload *CreateRoomOKBody `json:"body,omitempty"`
}

// NewCreateRoomOK creates CreateRoomOK with default headers values
func NewCreateRoomOK() *CreateRoomOK {

	return &CreateRoomOK{}
}

// WithPayload adds the payload to the create room o k response
func (o *CreateRoomOK) WithPayload(payload *CreateRoomOKBody) *CreateRoomOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create room o k response
func (o *CreateRoomOK) SetPayload(payload *CreateRoomOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRoomOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateRoomBadRequestCode is the HTTP code returned for type CreateRoomBadRequest
const CreateRoomBadRequestCode int = 400

/*
CreateRoomBadRequest Incorrect data

swagger:response createRoomBadRequest
*/
type CreateRoomBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateRoomBadRequest creates CreateRoomBadRequest with default headers values
func NewCreateRoomBadRequest() *CreateRoomBadRequest {

	return &CreateRoomBadRequest{}
}

// WithPayload adds the payload to the create room bad request response
func (o *CreateRoomBadRequest) WithPayload(payload *models.Error) *CreateRoomBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create room bad request response
func (o *CreateRoomBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRoomBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateRoomForbiddenCode is the HTTP code returned for type CreateRoomForbidden
const CreateRoomForbiddenCode int = 403

/*
CreateRoomForbidden No access

swagger:response createRoomForbidden
*/
type CreateRoomForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateRoomForbidden creates CreateRoomForbidden with default headers values
func NewCreateRoomForbidden() *CreateRoomForbidden {

	return &CreateRoomForbidden{}
}

// WithPayload adds the payload to the create room forbidden response
func (o *CreateRoomForbidden) WithPayload(payload *models.Error) *CreateRoomForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create room forbidden response
func (o *CreateRoomForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRoomForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
