// Code generated by go-swagger; DO NOT EDIT.

package room

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRoomByIDHandlerFunc turns a function with the right signature into a get room by id handler
type GetRoomByIDHandlerFunc func(GetRoomByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRoomByIDHandlerFunc) Handle(params GetRoomByIDParams) middleware.Responder {
	return fn(params)
}

// GetRoomByIDHandler interface for that can handle valid get room by id params
type GetRoomByIDHandler interface {
	Handle(GetRoomByIDParams) middleware.Responder
}

// NewGetRoomByID creates a new http.Handler for the get room by id operation
func NewGetRoomByID(ctx *middleware.Context, handler GetRoomByIDHandler) *GetRoomByID {
	return &GetRoomByID{Context: ctx, Handler: handler}
}

/*
	GetRoomByID swagger:route GET /hotel/room/{room_id} room getRoomById

Get room info by id
*/
type GetRoomByID struct {
	Context *middleware.Context
	Handler GetRoomByIDHandler
}

func (o *GetRoomByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetRoomByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
