// Code generated by go-swagger; DO NOT EDIT.

package room

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/h4x4d/go_hsse_hotels/hotel/internal/models"
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateRoomOKCode is the HTTP code returned for type UpdateRoomOK
const UpdateRoomOKCode int = 200

/*
UpdateRoomOK successful operation

swagger:response updateRoomOK
*/
type UpdateRoomOK struct {

	/*
	  In: Body
	*/
	Payload *UpdateRoomOKBody `json:"body,omitempty"`
}

// NewUpdateRoomOK creates UpdateRoomOK with default headers values
func NewUpdateRoomOK() *UpdateRoomOK {

	return &UpdateRoomOK{}
}

// WithPayload adds the payload to the update room o k response
func (o *UpdateRoomOK) WithPayload(payload *UpdateRoomOKBody) *UpdateRoomOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update room o k response
func (o *UpdateRoomOK) SetPayload(payload *UpdateRoomOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRoomOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRoomForbiddenCode is the HTTP code returned for type UpdateRoomForbidden
const UpdateRoomForbiddenCode int = 403

/*
UpdateRoomForbidden No access

swagger:response updateRoomForbidden
*/
type UpdateRoomForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateRoomForbidden creates UpdateRoomForbidden with default headers values
func NewUpdateRoomForbidden() *UpdateRoomForbidden {

	return &UpdateRoomForbidden{}
}

// WithPayload adds the payload to the update room forbidden response
func (o *UpdateRoomForbidden) WithPayload(payload *models.Error) *UpdateRoomForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update room forbidden response
func (o *UpdateRoomForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRoomForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRoomMethodNotAllowedCode is the HTTP code returned for type UpdateRoomMethodNotAllowed
const UpdateRoomMethodNotAllowedCode int = 405

/*
UpdateRoomMethodNotAllowed Incorrect data

swagger:response updateRoomMethodNotAllowed
*/
type UpdateRoomMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateRoomMethodNotAllowed creates UpdateRoomMethodNotAllowed with default headers values
func NewUpdateRoomMethodNotAllowed() *UpdateRoomMethodNotAllowed {

	return &UpdateRoomMethodNotAllowed{}
}

// WithPayload adds the payload to the update room method not allowed response
func (o *UpdateRoomMethodNotAllowed) WithPayload(payload *models.Error) *UpdateRoomMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update room method not allowed response
func (o *UpdateRoomMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRoomMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
