// Code generated by go-swagger; DO NOT EDIT.

package room

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/go_hsse_hotels/hotel/internal/models"
)

// UpdateRoomOKCode is the HTTP code returned for type UpdateRoomOK
const UpdateRoomOKCode int = 200

/*
UpdateRoomOK successful operation

swagger:response updateRoomOK
*/
type UpdateRoomOK struct {

	/*
	  In: Body
	*/
	Payload *UpdateRoomOKBody `json:"body,omitempty"`
}

// NewUpdateRoomOK creates UpdateRoomOK with default headers values
func NewUpdateRoomOK() *UpdateRoomOK {

	return &UpdateRoomOK{}
}

// WithPayload adds the payload to the update room o k response
func (o *UpdateRoomOK) WithPayload(payload *UpdateRoomOKBody) *UpdateRoomOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update room o k response
func (o *UpdateRoomOK) SetPayload(payload *UpdateRoomOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRoomOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRoomBadRequestCode is the HTTP code returned for type UpdateRoomBadRequest
const UpdateRoomBadRequestCode int = 400

/*
UpdateRoomBadRequest Incorrect data

swagger:response updateRoomBadRequest
*/
type UpdateRoomBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateRoomBadRequest creates UpdateRoomBadRequest with default headers values
func NewUpdateRoomBadRequest() *UpdateRoomBadRequest {

	return &UpdateRoomBadRequest{}
}

// WithPayload adds the payload to the update room bad request response
func (o *UpdateRoomBadRequest) WithPayload(payload *models.Error) *UpdateRoomBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update room bad request response
func (o *UpdateRoomBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRoomBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRoomForbiddenCode is the HTTP code returned for type UpdateRoomForbidden
const UpdateRoomForbiddenCode int = 403

/*
UpdateRoomForbidden No access

swagger:response updateRoomForbidden
*/
type UpdateRoomForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateRoomForbidden creates UpdateRoomForbidden with default headers values
func NewUpdateRoomForbidden() *UpdateRoomForbidden {

	return &UpdateRoomForbidden{}
}

// WithPayload adds the payload to the update room forbidden response
func (o *UpdateRoomForbidden) WithPayload(payload *models.Error) *UpdateRoomForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update room forbidden response
func (o *UpdateRoomForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRoomForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
