// Code generated by go-swagger; DO NOT EDIT.

// Package restapi hotels.hotel
//
//	MTS HSSE Go project | Hotel svc
//	Schemes:
//	  http
//	Host: example.com
//	BasePath: /
//	Version: 0.2.2
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
