---
swagger: "2.0"
info:
  description: "Swagger for MTS HSSE Golang project | Booking svc"
  version: "0.1.0"
  title: "H(SSE)OTELS | Booking svc"
# host: "127.0.0.1:8889"
# basePath: "/v2"
tags:
  - name: "customer"
    description: "Customer operations"
  - name: "hotelier"
    description: "Hotelier operations"
schemes:
  - "https"
  - "http"
paths:
  /booking/{booking_id}:
    get:
      tags:
        - "customer"
        - "hotelier"
      summary: "Get booking info by id"
      operationId: "get_booking_by_id"
      produces:
        - "application/json"
      parameters:
        - name: "booking_id"
          in: "path"
          description: "ID of booking to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Booking"
        404:
          description: "Booking not found"
        403:
          description: "No access"
      security:
        - api_key: []

    delete:
      tags:
        - "customer"
        - "hotelier"
      summary: "Delete booking info by id"
      operationId: "delete_booking_by_id"
      produces:
        - "application/json"
      parameters:
        - name: "booking_id"
          in: "path"
          description: "ID of booking to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
        404:
          description: "Booking not found"
        403:
          description: "No access"
      security:
        - api_key: []


  /booking:
    get:
      tags:
        - "customer"
        - "hotelier"
      summary: "Get suitable bookings"
      operationId: "get_booking"
      produces:
        - "application/json"
      parameters:
        - name: "hotel_id"
          in: "query"
          type: "integer"
        - name: "room_id"
          in: "query"
          type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Booking"
        403:
          description: "No access"
        404:
          description: "Id not found"
    post:
      tags:
        - "customer"
      summary: "Create booking"
      operationId: "create_booking"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "object"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Booking"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
        405:
          description: "Incorrect data"
      security:
        - api_key: []
    put:
      tags:
        - "customer"
        - "hotelier"
      summary: "Update booking"
      operationId: "update_booking"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "object"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Booking"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"

        403:
          description: "No access"
        405:
          description: "Incorrect data"
      security:
        - api_key: []


securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Booking:
    type: "object"
    required:
      - "date"
      - "room_id"
      - "hotel_id"
      - "status"
    properties:
      id:
        type: "integer"
        format: "int64"
      room_id:
        type: "integer"
        format: "int64"
      hotel_id:
        type: "integer"
        format: "int64"
      user_id:
        type: "integer"
        format: "int64"
      status:
        type: "string"
        description: "status of booking"
        enum:
          - "Unpayed"
          - "Confirming"
          - "Confirmed"
          - "Canceled"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      telegram:
        type: "string"
