---
swagger: "2.0"
info:
  description: "MTS HSSE Go project | Booking svc"
  version: "0.2.2"
  title: "hotels.booking"
# host: "127.0.0.1:8889"
# basePath: "/v2"
tags:
  - name: "customer"
    description: "Customer operations"
  - name: "hotelier"
    description: "Hotelier operations"
schemes:
  #  - "https"
  - "http"
paths:
  /booking/{booking_id}:
    get:
      tags:
        - "customer"
        - "hotelier"
      summary: "Get booking info by id"
      operationId: "get_booking_by_id"
      produces:
        - "application/json"
      parameters:
        - name: "booking_id"
          in: "path"
          description: "ID of booking to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Booking"
        404:
          description: "Booking not found"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "No access"
          schema:
            $ref: "#/definitions/Error"
      security:
        - api_key: [ ]

    put:
      tags:
        - "customer"
        - "hotelier"
      summary: "Update booking"
      operationId: "update_booking"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "booking_id"
          in: "path"
          description: "ID of booking to change"
          required: true
          type: "integer"
          format: "int64"
        - name: "object"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Booking"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              booking_id:
                type: "integer"
                format: "int64"
        403:
          description: "No access"
          schema:
            $ref: "#/definitions/Error"
        405:
          description: "Incorrect data"
          schema:
            $ref: "#/definitions/Error"
      security:
        - api_key: [ ]

    delete:
      tags:
        - "customer"
        - "hotelier"
      summary: "Delete booking info by id"
      operationId: "delete_booking_by_id"
      produces:
        - "application/json"
      parameters:
        - name: "booking_id"
          in: "path"
          description: "ID of booking to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
        404:
          description: "Booking not found"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "No access"
          schema:
            $ref: "#/definitions/Error"
      security:
        - api_key: [ ]


  /booking:
    get:
      tags:
        - "customer"
        - "hotelier"
      summary: "Get suitable bookings"
      operationId: "get_booking"
      produces:
        - "application/json"
      parameters:
        - name: "hotel_id"
          in: "query"
          type: "integer"
          format: "int64"
        - name: "room_id"
          in: "query"
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Booking"
        403:
          description: "No access"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Booking not found"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - "customer"
      summary: "Create booking"
      operationId: "create_booking"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "object"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Booking"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              booking_id:
                type: "integer"
                format: "int64"
        405:
          description: "Incorrect data"
          schema:
            $ref: "#/definitions/Error"
      security:
        - api_key: [ ]

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Booking:
    type: "object"
    required:
      - "date_from"
      - "date_to"
      - "room_id"
      - "hotel_id"
      - "status"
    properties:
      date_from:
        type: "string"
        pattern: ^\d{4}-\d{2}-\d{2}$
        example: "2024-12-31"
      date_to:
        type: "string"
        pattern: ^\d{4}-\d{2}-\d{2}$
        example: "2025-01-11"
      booking_id:
        type: "integer"
        format: "int64"
      room_id:
        type: "integer"
        format: "int64"
      hotel_id:
        type: "integer"
        format: "int64"
      user_id:
        type: "integer"
        format: "int64"
      status:
        type: "string"
        description: "status of booking"
        enum:
          - "Unpayed"
          - "Confirming"
          - "Confirmed"
          - "Canceled"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      role:
        type: "string"
        enum:
          - "customer"
          - "hotelier"
      name:
        type: "string"
      telegram:
        type: "string"
  Error:
    type: "object"
    required:
      - "error_status_code"
    properties:
      error_message:
        type: "string"
      error_status_code:
        type: integer
